#pragma once
#include <sstream>
#include <iomanip>
#include <windows.h>
#include <string>
#include <vector>
#include <cstdarg>
#include <memory>
#include <iostream>
#include <thread>
#include <chrono>
#include <algorithm>
#include "database.h"
#include "smtp.h"
#include "manager.h"
#include "crypt.h"
#include "misc.h"
#include "utils.h"
#include "debug.h"
#include <regex>
