#pragma once
#include <string>
#include <fstream>
#include <algorithm>
#include <iostream>
#include <unordered_map>
#include <windows.h>
#include <vector>
#include "core\models\user.h"
#include "core\models\movie.h"
#include "core\models\show.h"
#include "core\models\booking.h"
#include "core\utils.h"
#include "core\misc.h"
#include "core\smtp.h"
#include "core\debug.h"
#include <regex>